### ISSUE TITLE
FIFO broadcast and Uniform FIFO broadcast error

### ISSUE THREAD

**Issue by DCamma** [FrancescoSaverioZuppichini/Distributed-Algorithm-USI-2018#1]
You wrote:
 - *FIFO order* : if a **correct** `p` broadcast `m` before `m'` then no **correct** `p` delivers `m` before `m'`

but should be:
 - *FIFO order* : if a **correct** `p` broadcast `m` before `m'` then no **correct** `p` delivers `m'` before `m`

similarly for the Uniform FIFO broadcast

**Comment by FrancescoSaverioZuppichini** [comment]
You are correct 👍
